/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Base Code API
 * The Base Code API description
 * OpenAPI spec version: 1.0
 */
import axios from 'axios';
import type { AxiosError, AxiosRequestConfig, AxiosResponse } from 'axios';
import useSwr from 'swr';
import type { Arguments, Key, SWRConfiguration } from 'swr';
import useSWRMutation from 'swr/mutation';
import type { SWRMutationConfiguration } from 'swr/mutation';
import type {
  AddAllowedIpDto,
  AdminSettingControllerFindAllParams,
  BulkUpdateSettingDto,
  ClientErrorDto,
  CreateUserDto,
  FileControllerUploadFileParams,
  ForgotPasswordDto,
  GoogleLoginDto,
  LoginDto,
  RegisterDto,
  ResetPasswordDto,
  SettingControllerFindAllParams,
  SystemLogControllerCleanupParams,
  SystemLogControllerStatsParams,
  UpdateMaintenanceMessageDto,
  UpdateProfileDto,
  UpdateSettingDto,
  UpdateUserDto
} from './api-schemas';

export const appControllerGetHello = (
  options?: AxiosRequestConfig
): Promise<AxiosResponse<void>> => {
  return axios.get('/', options);
};

export const getAppControllerGetHelloKey = () => ['/'] as const;

export type AppControllerGetHelloQueryResult = NonNullable<
  Awaited<ReturnType<typeof appControllerGetHello>>
>;
export type AppControllerGetHelloQueryError = AxiosError<unknown>;

export const useAppControllerGetHello = <TError = AxiosError<unknown>>(options?: {
  swr?: SWRConfiguration<Awaited<ReturnType<typeof appControllerGetHello>>, TError> & {
    swrKey?: Key;
    enabled?: boolean;
  };
  axios?: AxiosRequestConfig;
}) => {
  const { swr: swrOptions, axios: axiosOptions } = options ?? {};

  const isEnabled = swrOptions?.enabled !== false;
  const swrKey = swrOptions?.swrKey ?? (() => (isEnabled ? getAppControllerGetHelloKey() : null));
  const swrFn = () => appControllerGetHello(axiosOptions);

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query
  };
};

export const authControllerLogin = (
  loginDto: LoginDto,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<void>> => {
  return axios.post('/auth/login', loginDto, options);
};

export const getAuthControllerLoginMutationFetcher = (options?: AxiosRequestConfig) => {
  return (_: string, { arg }: { arg: LoginDto }): Promise<AxiosResponse<void>> => {
    return authControllerLogin(arg, options);
  };
};
export const getAuthControllerLoginMutationKey = () => '/auth/login' as const;

export type AuthControllerLoginMutationResult = NonNullable<
  Awaited<ReturnType<typeof authControllerLogin>>
>;
export type AuthControllerLoginMutationError = AxiosError<unknown>;

export const useAuthControllerLogin = <TError = AxiosError<unknown>>(options?: {
  swr?: SWRMutationConfiguration<
    Awaited<ReturnType<typeof authControllerLogin>>,
    TError,
    string,
    LoginDto,
    Awaited<ReturnType<typeof authControllerLogin>>
  > & { swrKey?: string };
  axios?: AxiosRequestConfig;
}) => {
  const { swr: swrOptions, axios: axiosOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getAuthControllerLoginMutationKey();
  const swrFn = getAuthControllerLoginMutationFetcher(axiosOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query
  };
};

export const adminAuthControllerAdminLogin = (
  loginDto: LoginDto,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<void>> => {
  return axios.post('/auth/admin/login', loginDto, options);
};

export const getAdminAuthControllerAdminLoginMutationFetcher = (options?: AxiosRequestConfig) => {
  return (_: string, { arg }: { arg: LoginDto }): Promise<AxiosResponse<void>> => {
    return adminAuthControllerAdminLogin(arg, options);
  };
};
export const getAdminAuthControllerAdminLoginMutationKey = () => '/auth/admin/login' as const;

export type AdminAuthControllerAdminLoginMutationResult = NonNullable<
  Awaited<ReturnType<typeof adminAuthControllerAdminLogin>>
>;
export type AdminAuthControllerAdminLoginMutationError = AxiosError<unknown>;

export const useAdminAuthControllerAdminLogin = <TError = AxiosError<unknown>>(options?: {
  swr?: SWRMutationConfiguration<
    Awaited<ReturnType<typeof adminAuthControllerAdminLogin>>,
    TError,
    string,
    LoginDto,
    Awaited<ReturnType<typeof adminAuthControllerAdminLogin>>
  > & { swrKey?: string };
  axios?: AxiosRequestConfig;
}) => {
  const { swr: swrOptions, axios: axiosOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getAdminAuthControllerAdminLoginMutationKey();
  const swrFn = getAdminAuthControllerAdminLoginMutationFetcher(axiosOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query
  };
};

export const authControllerRegister = (
  registerDto: RegisterDto,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<void>> => {
  return axios.post('/auth/register', registerDto, options);
};

export const getAuthControllerRegisterMutationFetcher = (options?: AxiosRequestConfig) => {
  return (_: string, { arg }: { arg: RegisterDto }): Promise<AxiosResponse<void>> => {
    return authControllerRegister(arg, options);
  };
};
export const getAuthControllerRegisterMutationKey = () => '/auth/register' as const;

export type AuthControllerRegisterMutationResult = NonNullable<
  Awaited<ReturnType<typeof authControllerRegister>>
>;
export type AuthControllerRegisterMutationError = AxiosError<unknown>;

export const useAuthControllerRegister = <TError = AxiosError<unknown>>(options?: {
  swr?: SWRMutationConfiguration<
    Awaited<ReturnType<typeof authControllerRegister>>,
    TError,
    string,
    RegisterDto,
    Awaited<ReturnType<typeof authControllerRegister>>
  > & { swrKey?: string };
  axios?: AxiosRequestConfig;
}) => {
  const { swr: swrOptions, axios: axiosOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getAuthControllerRegisterMutationKey();
  const swrFn = getAuthControllerRegisterMutationFetcher(axiosOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query
  };
};

export const authControllerLoginWithGoogle = (
  googleLoginDto: GoogleLoginDto,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<void>> => {
  return axios.post('/auth/google', googleLoginDto, options);
};

export const getAuthControllerLoginWithGoogleMutationFetcher = (options?: AxiosRequestConfig) => {
  return (_: string, { arg }: { arg: GoogleLoginDto }): Promise<AxiosResponse<void>> => {
    return authControllerLoginWithGoogle(arg, options);
  };
};
export const getAuthControllerLoginWithGoogleMutationKey = () => '/auth/google' as const;

export type AuthControllerLoginWithGoogleMutationResult = NonNullable<
  Awaited<ReturnType<typeof authControllerLoginWithGoogle>>
>;
export type AuthControllerLoginWithGoogleMutationError = AxiosError<unknown>;

export const useAuthControllerLoginWithGoogle = <TError = AxiosError<unknown>>(options?: {
  swr?: SWRMutationConfiguration<
    Awaited<ReturnType<typeof authControllerLoginWithGoogle>>,
    TError,
    string,
    GoogleLoginDto,
    Awaited<ReturnType<typeof authControllerLoginWithGoogle>>
  > & { swrKey?: string };
  axios?: AxiosRequestConfig;
}) => {
  const { swr: swrOptions, axios: axiosOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getAuthControllerLoginWithGoogleMutationKey();
  const swrFn = getAuthControllerLoginWithGoogleMutationFetcher(axiosOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query
  };
};

export const authControllerMe = (options?: AxiosRequestConfig): Promise<AxiosResponse<void>> => {
  return axios.get('/auth/me', options);
};

export const getAuthControllerMeKey = () => ['/auth/me'] as const;

export type AuthControllerMeQueryResult = NonNullable<Awaited<ReturnType<typeof authControllerMe>>>;
export type AuthControllerMeQueryError = AxiosError<unknown>;

export const useAuthControllerMe = <TError = AxiosError<unknown>>(options?: {
  swr?: SWRConfiguration<Awaited<ReturnType<typeof authControllerMe>>, TError> & {
    swrKey?: Key;
    enabled?: boolean;
  };
  axios?: AxiosRequestConfig;
}) => {
  const { swr: swrOptions, axios: axiosOptions } = options ?? {};

  const isEnabled = swrOptions?.enabled !== false;
  const swrKey = swrOptions?.swrKey ?? (() => (isEnabled ? getAuthControllerMeKey() : null));
  const swrFn = () => authControllerMe(axiosOptions);

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query
  };
};

export const authControllerLogout = (
  options?: AxiosRequestConfig
): Promise<AxiosResponse<void>> => {
  return axios.post('/auth/logout', undefined, options);
};

export const getAuthControllerLogoutMutationFetcher = (options?: AxiosRequestConfig) => {
  return (_: string, __: { arg: Arguments }): Promise<AxiosResponse<void>> => {
    return authControllerLogout(options);
  };
};
export const getAuthControllerLogoutMutationKey = () => '/auth/logout' as const;

export type AuthControllerLogoutMutationResult = NonNullable<
  Awaited<ReturnType<typeof authControllerLogout>>
>;
export type AuthControllerLogoutMutationError = AxiosError<unknown>;

export const useAuthControllerLogout = <TError = AxiosError<unknown>>(options?: {
  swr?: SWRMutationConfiguration<
    Awaited<ReturnType<typeof authControllerLogout>>,
    TError,
    string,
    Arguments,
    Awaited<ReturnType<typeof authControllerLogout>>
  > & { swrKey?: string };
  axios?: AxiosRequestConfig;
}) => {
  const { swr: swrOptions, axios: axiosOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getAuthControllerLogoutMutationKey();
  const swrFn = getAuthControllerLogoutMutationFetcher(axiosOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query
  };
};

export const authControllerForgotPassword = (
  forgotPasswordDto: ForgotPasswordDto,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<void>> => {
  return axios.post('/auth/forgot-password', forgotPasswordDto, options);
};

export const getAuthControllerForgotPasswordMutationFetcher = (options?: AxiosRequestConfig) => {
  return (_: string, { arg }: { arg: ForgotPasswordDto }): Promise<AxiosResponse<void>> => {
    return authControllerForgotPassword(arg, options);
  };
};
export const getAuthControllerForgotPasswordMutationKey = () => '/auth/forgot-password' as const;

export type AuthControllerForgotPasswordMutationResult = NonNullable<
  Awaited<ReturnType<typeof authControllerForgotPassword>>
>;
export type AuthControllerForgotPasswordMutationError = AxiosError<unknown>;

export const useAuthControllerForgotPassword = <TError = AxiosError<unknown>>(options?: {
  swr?: SWRMutationConfiguration<
    Awaited<ReturnType<typeof authControllerForgotPassword>>,
    TError,
    string,
    ForgotPasswordDto,
    Awaited<ReturnType<typeof authControllerForgotPassword>>
  > & { swrKey?: string };
  axios?: AxiosRequestConfig;
}) => {
  const { swr: swrOptions, axios: axiosOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getAuthControllerForgotPasswordMutationKey();
  const swrFn = getAuthControllerForgotPasswordMutationFetcher(axiosOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query
  };
};

export const authControllerVerifyResetToken = (
  options?: AxiosRequestConfig
): Promise<AxiosResponse<void>> => {
  return axios.get('/auth/reset-password/verify', options);
};

export const getAuthControllerVerifyResetTokenKey = () => ['/auth/reset-password/verify'] as const;

export type AuthControllerVerifyResetTokenQueryResult = NonNullable<
  Awaited<ReturnType<typeof authControllerVerifyResetToken>>
>;
export type AuthControllerVerifyResetTokenQueryError = AxiosError<unknown>;

export const useAuthControllerVerifyResetToken = <TError = AxiosError<unknown>>(options?: {
  swr?: SWRConfiguration<Awaited<ReturnType<typeof authControllerVerifyResetToken>>, TError> & {
    swrKey?: Key;
    enabled?: boolean;
  };
  axios?: AxiosRequestConfig;
}) => {
  const { swr: swrOptions, axios: axiosOptions } = options ?? {};

  const isEnabled = swrOptions?.enabled !== false;
  const swrKey =
    swrOptions?.swrKey ?? (() => (isEnabled ? getAuthControllerVerifyResetTokenKey() : null));
  const swrFn = () => authControllerVerifyResetToken(axiosOptions);

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query
  };
};

export const authControllerResetPassword = (
  resetPasswordDto: ResetPasswordDto,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<void>> => {
  return axios.post('/auth/reset-password', resetPasswordDto, options);
};

export const getAuthControllerResetPasswordMutationFetcher = (options?: AxiosRequestConfig) => {
  return (_: string, { arg }: { arg: ResetPasswordDto }): Promise<AxiosResponse<void>> => {
    return authControllerResetPassword(arg, options);
  };
};
export const getAuthControllerResetPasswordMutationKey = () => '/auth/reset-password' as const;

export type AuthControllerResetPasswordMutationResult = NonNullable<
  Awaited<ReturnType<typeof authControllerResetPassword>>
>;
export type AuthControllerResetPasswordMutationError = AxiosError<unknown>;

export const useAuthControllerResetPassword = <TError = AxiosError<unknown>>(options?: {
  swr?: SWRMutationConfiguration<
    Awaited<ReturnType<typeof authControllerResetPassword>>,
    TError,
    string,
    ResetPasswordDto,
    Awaited<ReturnType<typeof authControllerResetPassword>>
  > & { swrKey?: string };
  axios?: AxiosRequestConfig;
}) => {
  const { swr: swrOptions, axios: axiosOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getAuthControllerResetPasswordMutationKey();
  const swrFn = getAuthControllerResetPasswordMutationFetcher(axiosOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query
  };
};

export const loginControllerLogin = (
  loginDto: LoginDto,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<void>> => {
  return axios.post('/login', loginDto, options);
};

export const getLoginControllerLoginMutationFetcher = (options?: AxiosRequestConfig) => {
  return (_: string, { arg }: { arg: LoginDto }): Promise<AxiosResponse<void>> => {
    return loginControllerLogin(arg, options);
  };
};
export const getLoginControllerLoginMutationKey = () => '/login' as const;

export type LoginControllerLoginMutationResult = NonNullable<
  Awaited<ReturnType<typeof loginControllerLogin>>
>;
export type LoginControllerLoginMutationError = AxiosError<unknown>;

export const useLoginControllerLogin = <TError = AxiosError<unknown>>(options?: {
  swr?: SWRMutationConfiguration<
    Awaited<ReturnType<typeof loginControllerLogin>>,
    TError,
    string,
    LoginDto,
    Awaited<ReturnType<typeof loginControllerLogin>>
  > & { swrKey?: string };
  axios?: AxiosRequestConfig;
}) => {
  const { swr: swrOptions, axios: axiosOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getLoginControllerLoginMutationKey();
  const swrFn = getLoginControllerLoginMutationFetcher(axiosOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query
  };
};

/**
 * @summary Lấy thông tin cá nhân
 */
export const userControllerGetMe = (options?: AxiosRequestConfig): Promise<AxiosResponse<void>> => {
  return axios.get('/users/me', options);
};

export const getUserControllerGetMeKey = () => ['/users/me'] as const;

export type UserControllerGetMeQueryResult = NonNullable<
  Awaited<ReturnType<typeof userControllerGetMe>>
>;
export type UserControllerGetMeQueryError = AxiosError<unknown>;

/**
 * @summary Lấy thông tin cá nhân
 */
export const useUserControllerGetMe = <TError = AxiosError<unknown>>(options?: {
  swr?: SWRConfiguration<Awaited<ReturnType<typeof userControllerGetMe>>, TError> & {
    swrKey?: Key;
    enabled?: boolean;
  };
  axios?: AxiosRequestConfig;
}) => {
  const { swr: swrOptions, axios: axiosOptions } = options ?? {};

  const isEnabled = swrOptions?.enabled !== false;
  const swrKey = swrOptions?.swrKey ?? (() => (isEnabled ? getUserControllerGetMeKey() : null));
  const swrFn = () => userControllerGetMe(axiosOptions);

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query
  };
};

/**
 * @summary Cập nhật thông tin cá nhân
 */
export const userControllerUpdateMe = (
  updateProfileDto: UpdateProfileDto,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<void>> => {
  return axios.put('/users/me', updateProfileDto, options);
};

export const getUserControllerUpdateMeMutationFetcher = (options?: AxiosRequestConfig) => {
  return (_: string, { arg }: { arg: UpdateProfileDto }): Promise<AxiosResponse<void>> => {
    return userControllerUpdateMe(arg, options);
  };
};
export const getUserControllerUpdateMeMutationKey = () => '/users/me' as const;

export type UserControllerUpdateMeMutationResult = NonNullable<
  Awaited<ReturnType<typeof userControllerUpdateMe>>
>;
export type UserControllerUpdateMeMutationError = AxiosError<unknown>;

/**
 * @summary Cập nhật thông tin cá nhân
 */
export const useUserControllerUpdateMe = <TError = AxiosError<unknown>>(options?: {
  swr?: SWRMutationConfiguration<
    Awaited<ReturnType<typeof userControllerUpdateMe>>,
    TError,
    string,
    UpdateProfileDto,
    Awaited<ReturnType<typeof userControllerUpdateMe>>
  > & { swrKey?: string };
  axios?: AxiosRequestConfig;
}) => {
  const { swr: swrOptions, axios: axiosOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getUserControllerUpdateMeMutationKey();
  const swrFn = getUserControllerUpdateMeMutationFetcher(axiosOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query
  };
};

/**
 * @summary Admin lấy thông tin người dùng theo ID
 */
export const userControllerFindById = (
  id: string,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<void>> => {
  return axios.get(`/users/${id}`, options);
};

export const getUserControllerFindByIdKey = (id: string) => [`/users/${id}`] as const;

export type UserControllerFindByIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof userControllerFindById>>
>;
export type UserControllerFindByIdQueryError = AxiosError<unknown>;

/**
 * @summary Admin lấy thông tin người dùng theo ID
 */
export const useUserControllerFindById = <TError = AxiosError<unknown>>(
  id: string,
  options?: {
    swr?: SWRConfiguration<Awaited<ReturnType<typeof userControllerFindById>>, TError> & {
      swrKey?: Key;
      enabled?: boolean;
    };
    axios?: AxiosRequestConfig;
  }
) => {
  const { swr: swrOptions, axios: axiosOptions } = options ?? {};

  const isEnabled = swrOptions?.enabled !== false && !!id;
  const swrKey =
    swrOptions?.swrKey ?? (() => (isEnabled ? getUserControllerFindByIdKey(id) : null));
  const swrFn = () => userControllerFindById(id, axiosOptions);

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query
  };
};

/**
 * @summary Admin cập nhật thông tin người dùng
 */
export const userControllerUpdate = (
  id: string,
  updateUserDto: UpdateUserDto,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<void>> => {
  return axios.put(`/users/${id}`, updateUserDto, options);
};

export const getUserControllerUpdateMutationFetcher = (
  id: string,
  options?: AxiosRequestConfig
) => {
  return (_: string, { arg }: { arg: UpdateUserDto }): Promise<AxiosResponse<void>> => {
    return userControllerUpdate(id, arg, options);
  };
};
export const getUserControllerUpdateMutationKey = (id: string) => `/users/${id}` as const;

export type UserControllerUpdateMutationResult = NonNullable<
  Awaited<ReturnType<typeof userControllerUpdate>>
>;
export type UserControllerUpdateMutationError = AxiosError<unknown>;

/**
 * @summary Admin cập nhật thông tin người dùng
 */
export const useUserControllerUpdate = <TError = AxiosError<unknown>>(
  id: string,
  options?: {
    swr?: SWRMutationConfiguration<
      Awaited<ReturnType<typeof userControllerUpdate>>,
      TError,
      string,
      UpdateUserDto,
      Awaited<ReturnType<typeof userControllerUpdate>>
    > & { swrKey?: string };
    axios?: AxiosRequestConfig;
  }
) => {
  const { swr: swrOptions, axios: axiosOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getUserControllerUpdateMutationKey(id);
  const swrFn = getUserControllerUpdateMutationFetcher(id, axiosOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query
  };
};

export const adminUserControllerSearch = (
  options?: AxiosRequestConfig
): Promise<AxiosResponse<void>> => {
  return axios.get('/admin/users', options);
};

export const getAdminUserControllerSearchKey = () => ['/admin/users'] as const;

export type AdminUserControllerSearchQueryResult = NonNullable<
  Awaited<ReturnType<typeof adminUserControllerSearch>>
>;
export type AdminUserControllerSearchQueryError = AxiosError<unknown>;

export const useAdminUserControllerSearch = <TError = AxiosError<unknown>>(options?: {
  swr?: SWRConfiguration<Awaited<ReturnType<typeof adminUserControllerSearch>>, TError> & {
    swrKey?: Key;
    enabled?: boolean;
  };
  axios?: AxiosRequestConfig;
}) => {
  const { swr: swrOptions, axios: axiosOptions } = options ?? {};

  const isEnabled = swrOptions?.enabled !== false;
  const swrKey =
    swrOptions?.swrKey ?? (() => (isEnabled ? getAdminUserControllerSearchKey() : null));
  const swrFn = () => adminUserControllerSearch(axiosOptions);

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query
  };
};

export const adminUserControllerCreate = (
  createUserDto: CreateUserDto,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<void>> => {
  return axios.post('/admin/users', createUserDto, options);
};

export const getAdminUserControllerCreateMutationFetcher = (options?: AxiosRequestConfig) => {
  return (_: string, { arg }: { arg: CreateUserDto }): Promise<AxiosResponse<void>> => {
    return adminUserControllerCreate(arg, options);
  };
};
export const getAdminUserControllerCreateMutationKey = () => '/admin/users' as const;

export type AdminUserControllerCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof adminUserControllerCreate>>
>;
export type AdminUserControllerCreateMutationError = AxiosError<unknown>;

export const useAdminUserControllerCreate = <TError = AxiosError<unknown>>(options?: {
  swr?: SWRMutationConfiguration<
    Awaited<ReturnType<typeof adminUserControllerCreate>>,
    TError,
    string,
    CreateUserDto,
    Awaited<ReturnType<typeof adminUserControllerCreate>>
  > & { swrKey?: string };
  axios?: AxiosRequestConfig;
}) => {
  const { swr: swrOptions, axios: axiosOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getAdminUserControllerCreateMutationKey();
  const swrFn = getAdminUserControllerCreateMutationFetcher(axiosOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query
  };
};

export const adminUserControllerFindById = (
  id: string,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<void>> => {
  return axios.get(`/admin/users/${id}`, options);
};

export const getAdminUserControllerFindByIdKey = (id: string) => [`/admin/users/${id}`] as const;

export type AdminUserControllerFindByIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof adminUserControllerFindById>>
>;
export type AdminUserControllerFindByIdQueryError = AxiosError<unknown>;

export const useAdminUserControllerFindById = <TError = AxiosError<unknown>>(
  id: string,
  options?: {
    swr?: SWRConfiguration<Awaited<ReturnType<typeof adminUserControllerFindById>>, TError> & {
      swrKey?: Key;
      enabled?: boolean;
    };
    axios?: AxiosRequestConfig;
  }
) => {
  const { swr: swrOptions, axios: axiosOptions } = options ?? {};

  const isEnabled = swrOptions?.enabled !== false && !!id;
  const swrKey =
    swrOptions?.swrKey ?? (() => (isEnabled ? getAdminUserControllerFindByIdKey(id) : null));
  const swrFn = () => adminUserControllerFindById(id, axiosOptions);

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query
  };
};

export const adminUserControllerUpdate = (
  id: string,
  updateUserDto: UpdateUserDto,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<void>> => {
  return axios.put(`/admin/users/${id}`, updateUserDto, options);
};

export const getAdminUserControllerUpdateMutationFetcher = (
  id: string,
  options?: AxiosRequestConfig
) => {
  return (_: string, { arg }: { arg: UpdateUserDto }): Promise<AxiosResponse<void>> => {
    return adminUserControllerUpdate(id, arg, options);
  };
};
export const getAdminUserControllerUpdateMutationKey = (id: string) =>
  `/admin/users/${id}` as const;

export type AdminUserControllerUpdateMutationResult = NonNullable<
  Awaited<ReturnType<typeof adminUserControllerUpdate>>
>;
export type AdminUserControllerUpdateMutationError = AxiosError<unknown>;

export const useAdminUserControllerUpdate = <TError = AxiosError<unknown>>(
  id: string,
  options?: {
    swr?: SWRMutationConfiguration<
      Awaited<ReturnType<typeof adminUserControllerUpdate>>,
      TError,
      string,
      UpdateUserDto,
      Awaited<ReturnType<typeof adminUserControllerUpdate>>
    > & { swrKey?: string };
    axios?: AxiosRequestConfig;
  }
) => {
  const { swr: swrOptions, axios: axiosOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getAdminUserControllerUpdateMutationKey(id);
  const swrFn = getAdminUserControllerUpdateMutationFetcher(id, axiosOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query
  };
};

export const adminUserControllerDelete = (
  id: string,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<void>> => {
  return axios.delete(`/admin/users/${id}`, options);
};

export const getAdminUserControllerDeleteMutationFetcher = (
  id: string,
  options?: AxiosRequestConfig
) => {
  return (_: string, __: { arg: Arguments }): Promise<AxiosResponse<void>> => {
    return adminUserControllerDelete(id, options);
  };
};
export const getAdminUserControllerDeleteMutationKey = (id: string) =>
  `/admin/users/${id}` as const;

export type AdminUserControllerDeleteMutationResult = NonNullable<
  Awaited<ReturnType<typeof adminUserControllerDelete>>
>;
export type AdminUserControllerDeleteMutationError = AxiosError<unknown>;

export const useAdminUserControllerDelete = <TError = AxiosError<unknown>>(
  id: string,
  options?: {
    swr?: SWRMutationConfiguration<
      Awaited<ReturnType<typeof adminUserControllerDelete>>,
      TError,
      string,
      Arguments,
      Awaited<ReturnType<typeof adminUserControllerDelete>>
    > & { swrKey?: string };
    axios?: AxiosRequestConfig;
  }
) => {
  const { swr: swrOptions, axios: axiosOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getAdminUserControllerDeleteMutationKey(id);
  const swrFn = getAdminUserControllerDeleteMutationFetcher(id, axiosOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query
  };
};

export const fileControllerUploadFile = (
  params: FileControllerUploadFileParams,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<void>> => {
  return axios.post('/files/upload', undefined, {
    ...options,
    params: { ...params, ...options?.params }
  });
};

export const getFileControllerUploadFileMutationFetcher = (
  params: FileControllerUploadFileParams,
  options?: AxiosRequestConfig
) => {
  return (_: string, __: { arg: Arguments }): Promise<AxiosResponse<void>> => {
    return fileControllerUploadFile(params, options);
  };
};
export const getFileControllerUploadFileMutationKey = () => '/files/upload' as const;

export type FileControllerUploadFileMutationResult = NonNullable<
  Awaited<ReturnType<typeof fileControllerUploadFile>>
>;
export type FileControllerUploadFileMutationError = AxiosError<unknown>;

export const useFileControllerUploadFile = <TError = AxiosError<unknown>>(
  params: FileControllerUploadFileParams,
  options?: {
    swr?: SWRMutationConfiguration<
      Awaited<ReturnType<typeof fileControllerUploadFile>>,
      TError,
      string,
      Arguments,
      Awaited<ReturnType<typeof fileControllerUploadFile>>
    > & { swrKey?: string };
    axios?: AxiosRequestConfig;
  }
) => {
  const { swr: swrOptions, axios: axiosOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getFileControllerUploadFileMutationKey();
  const swrFn = getFileControllerUploadFileMutationFetcher(params, axiosOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query
  };
};

export const fileControllerUploadAvatar = (
  options?: AxiosRequestConfig
): Promise<AxiosResponse<void>> => {
  return axios.post('/files/upload/avatar', undefined, options);
};

export const getFileControllerUploadAvatarMutationFetcher = (options?: AxiosRequestConfig) => {
  return (_: string, __: { arg: Arguments }): Promise<AxiosResponse<void>> => {
    return fileControllerUploadAvatar(options);
  };
};
export const getFileControllerUploadAvatarMutationKey = () => '/files/upload/avatar' as const;

export type FileControllerUploadAvatarMutationResult = NonNullable<
  Awaited<ReturnType<typeof fileControllerUploadAvatar>>
>;
export type FileControllerUploadAvatarMutationError = AxiosError<unknown>;

export const useFileControllerUploadAvatar = <TError = AxiosError<unknown>>(options?: {
  swr?: SWRMutationConfiguration<
    Awaited<ReturnType<typeof fileControllerUploadAvatar>>,
    TError,
    string,
    Arguments,
    Awaited<ReturnType<typeof fileControllerUploadAvatar>>
  > & { swrKey?: string };
  axios?: AxiosRequestConfig;
}) => {
  const { swr: swrOptions, axios: axiosOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getFileControllerUploadAvatarMutationKey();
  const swrFn = getFileControllerUploadAvatarMutationFetcher(axiosOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query
  };
};

export const fileControllerUploadInventoryImage = (
  options?: AxiosRequestConfig
): Promise<AxiosResponse<void>> => {
  return axios.post('/files/upload/inventory', undefined, options);
};

export const getFileControllerUploadInventoryImageMutationFetcher = (
  options?: AxiosRequestConfig
) => {
  return (_: string, __: { arg: Arguments }): Promise<AxiosResponse<void>> => {
    return fileControllerUploadInventoryImage(options);
  };
};
export const getFileControllerUploadInventoryImageMutationKey = () =>
  '/files/upload/inventory' as const;

export type FileControllerUploadInventoryImageMutationResult = NonNullable<
  Awaited<ReturnType<typeof fileControllerUploadInventoryImage>>
>;
export type FileControllerUploadInventoryImageMutationError = AxiosError<unknown>;

export const useFileControllerUploadInventoryImage = <TError = AxiosError<unknown>>(options?: {
  swr?: SWRMutationConfiguration<
    Awaited<ReturnType<typeof fileControllerUploadInventoryImage>>,
    TError,
    string,
    Arguments,
    Awaited<ReturnType<typeof fileControllerUploadInventoryImage>>
  > & { swrKey?: string };
  axios?: AxiosRequestConfig;
}) => {
  const { swr: swrOptions, axios: axiosOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getFileControllerUploadInventoryImageMutationKey();
  const swrFn = getFileControllerUploadInventoryImageMutationFetcher(axiosOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query
  };
};

export const fileControllerGetFileById = (
  id: string,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<void>> => {
  return axios.get(`/files/${id}`, options);
};

export const getFileControllerGetFileByIdKey = (id: string) => [`/files/${id}`] as const;

export type FileControllerGetFileByIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof fileControllerGetFileById>>
>;
export type FileControllerGetFileByIdQueryError = AxiosError<unknown>;

export const useFileControllerGetFileById = <TError = AxiosError<unknown>>(
  id: string,
  options?: {
    swr?: SWRConfiguration<Awaited<ReturnType<typeof fileControllerGetFileById>>, TError> & {
      swrKey?: Key;
      enabled?: boolean;
    };
    axios?: AxiosRequestConfig;
  }
) => {
  const { swr: swrOptions, axios: axiosOptions } = options ?? {};

  const isEnabled = swrOptions?.enabled !== false && !!id;
  const swrKey =
    swrOptions?.swrKey ?? (() => (isEnabled ? getFileControllerGetFileByIdKey(id) : null));
  const swrFn = () => fileControllerGetFileById(id, axiosOptions);

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query
  };
};

export const fileControllerDeleteFile = (
  id: string,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<void>> => {
  return axios.delete(`/files/${id}`, options);
};

export const getFileControllerDeleteFileMutationFetcher = (
  id: string,
  options?: AxiosRequestConfig
) => {
  return (_: string, __: { arg: Arguments }): Promise<AxiosResponse<void>> => {
    return fileControllerDeleteFile(id, options);
  };
};
export const getFileControllerDeleteFileMutationKey = (id: string) => `/files/${id}` as const;

export type FileControllerDeleteFileMutationResult = NonNullable<
  Awaited<ReturnType<typeof fileControllerDeleteFile>>
>;
export type FileControllerDeleteFileMutationError = AxiosError<unknown>;

export const useFileControllerDeleteFile = <TError = AxiosError<unknown>>(
  id: string,
  options?: {
    swr?: SWRMutationConfiguration<
      Awaited<ReturnType<typeof fileControllerDeleteFile>>,
      TError,
      string,
      Arguments,
      Awaited<ReturnType<typeof fileControllerDeleteFile>>
    > & { swrKey?: string };
    axios?: AxiosRequestConfig;
  }
) => {
  const { swr: swrOptions, axios: axiosOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getFileControllerDeleteFileMutationKey(id);
  const swrFn = getFileControllerDeleteFileMutationFetcher(id, axiosOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query
  };
};

export const fileControllerGetFileInfo = (
  id: string,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<void>> => {
  return axios.get(`/files/${id}/info`, options);
};

export const getFileControllerGetFileInfoKey = (id: string) => [`/files/${id}/info`] as const;

export type FileControllerGetFileInfoQueryResult = NonNullable<
  Awaited<ReturnType<typeof fileControllerGetFileInfo>>
>;
export type FileControllerGetFileInfoQueryError = AxiosError<unknown>;

export const useFileControllerGetFileInfo = <TError = AxiosError<unknown>>(
  id: string,
  options?: {
    swr?: SWRConfiguration<Awaited<ReturnType<typeof fileControllerGetFileInfo>>, TError> & {
      swrKey?: Key;
      enabled?: boolean;
    };
    axios?: AxiosRequestConfig;
  }
) => {
  const { swr: swrOptions, axios: axiosOptions } = options ?? {};

  const isEnabled = swrOptions?.enabled !== false && !!id;
  const swrKey =
    swrOptions?.swrKey ?? (() => (isEnabled ? getFileControllerGetFileInfoKey(id) : null));
  const swrFn = () => fileControllerGetFileInfo(id, axiosOptions);

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query
  };
};

export const settingControllerGetPublicSite = (
  options?: AxiosRequestConfig
): Promise<AxiosResponse<void>> => {
  return axios.get('/settings/public/site', options);
};

export const getSettingControllerGetPublicSiteKey = () => ['/settings/public/site'] as const;

export type SettingControllerGetPublicSiteQueryResult = NonNullable<
  Awaited<ReturnType<typeof settingControllerGetPublicSite>>
>;
export type SettingControllerGetPublicSiteQueryError = AxiosError<unknown>;

export const useSettingControllerGetPublicSite = <TError = AxiosError<unknown>>(options?: {
  swr?: SWRConfiguration<Awaited<ReturnType<typeof settingControllerGetPublicSite>>, TError> & {
    swrKey?: Key;
    enabled?: boolean;
  };
  axios?: AxiosRequestConfig;
}) => {
  const { swr: swrOptions, axios: axiosOptions } = options ?? {};

  const isEnabled = swrOptions?.enabled !== false;
  const swrKey =
    swrOptions?.swrKey ?? (() => (isEnabled ? getSettingControllerGetPublicSiteKey() : null));
  const swrFn = () => settingControllerGetPublicSite(axiosOptions);

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query
  };
};

export const settingControllerGetPublicAuth = (
  options?: AxiosRequestConfig
): Promise<AxiosResponse<void>> => {
  return axios.get('/settings/public/auth', options);
};

export const getSettingControllerGetPublicAuthKey = () => ['/settings/public/auth'] as const;

export type SettingControllerGetPublicAuthQueryResult = NonNullable<
  Awaited<ReturnType<typeof settingControllerGetPublicAuth>>
>;
export type SettingControllerGetPublicAuthQueryError = AxiosError<unknown>;

export const useSettingControllerGetPublicAuth = <TError = AxiosError<unknown>>(options?: {
  swr?: SWRConfiguration<Awaited<ReturnType<typeof settingControllerGetPublicAuth>>, TError> & {
    swrKey?: Key;
    enabled?: boolean;
  };
  axios?: AxiosRequestConfig;
}) => {
  const { swr: swrOptions, axios: axiosOptions } = options ?? {};

  const isEnabled = swrOptions?.enabled !== false;
  const swrKey =
    swrOptions?.swrKey ?? (() => (isEnabled ? getSettingControllerGetPublicAuthKey() : null));
  const swrFn = () => settingControllerGetPublicAuth(axiosOptions);

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query
  };
};

export const settingControllerFindAll = (
  params: SettingControllerFindAllParams,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<void>> => {
  return axios.get('/settings', {
    ...options,
    params: { ...params, ...options?.params }
  });
};

export const getSettingControllerFindAllKey = (params: SettingControllerFindAllParams) =>
  ['/settings', ...(params ? [params] : [])] as const;

export type SettingControllerFindAllQueryResult = NonNullable<
  Awaited<ReturnType<typeof settingControllerFindAll>>
>;
export type SettingControllerFindAllQueryError = AxiosError<unknown>;

export const useSettingControllerFindAll = <TError = AxiosError<unknown>>(
  params: SettingControllerFindAllParams,
  options?: {
    swr?: SWRConfiguration<Awaited<ReturnType<typeof settingControllerFindAll>>, TError> & {
      swrKey?: Key;
      enabled?: boolean;
    };
    axios?: AxiosRequestConfig;
  }
) => {
  const { swr: swrOptions, axios: axiosOptions } = options ?? {};

  const isEnabled = swrOptions?.enabled !== false;
  const swrKey =
    swrOptions?.swrKey ?? (() => (isEnabled ? getSettingControllerFindAllKey(params) : null));
  const swrFn = () => settingControllerFindAll(params, axiosOptions);

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query
  };
};

export const settingControllerFindByKey = (
  key: string,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<void>> => {
  return axios.get(`/settings/${key}`, options);
};

export const getSettingControllerFindByKeyKey = (key: string) => [`/settings/${key}`] as const;

export type SettingControllerFindByKeyQueryResult = NonNullable<
  Awaited<ReturnType<typeof settingControllerFindByKey>>
>;
export type SettingControllerFindByKeyQueryError = AxiosError<unknown>;

export const useSettingControllerFindByKey = <TError = AxiosError<unknown>>(
  key: string,
  options?: {
    swr?: SWRConfiguration<Awaited<ReturnType<typeof settingControllerFindByKey>>, TError> & {
      swrKey?: Key;
      enabled?: boolean;
    };
    axios?: AxiosRequestConfig;
  }
) => {
  const { swr: swrOptions, axios: axiosOptions } = options ?? {};

  const isEnabled = swrOptions?.enabled !== false && !!key;
  const swrKey =
    swrOptions?.swrKey ?? (() => (isEnabled ? getSettingControllerFindByKeyKey(key) : null));
  const swrFn = () => settingControllerFindByKey(key, axiosOptions);

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query
  };
};

export const adminSettingControllerFindAll = (
  params: AdminSettingControllerFindAllParams,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<void>> => {
  return axios.get('/admin/settings', {
    ...options,
    params: { ...params, ...options?.params }
  });
};

export const getAdminSettingControllerFindAllKey = (params: AdminSettingControllerFindAllParams) =>
  ['/admin/settings', ...(params ? [params] : [])] as const;

export type AdminSettingControllerFindAllQueryResult = NonNullable<
  Awaited<ReturnType<typeof adminSettingControllerFindAll>>
>;
export type AdminSettingControllerFindAllQueryError = AxiosError<unknown>;

export const useAdminSettingControllerFindAll = <TError = AxiosError<unknown>>(
  params: AdminSettingControllerFindAllParams,
  options?: {
    swr?: SWRConfiguration<Awaited<ReturnType<typeof adminSettingControllerFindAll>>, TError> & {
      swrKey?: Key;
      enabled?: boolean;
    };
    axios?: AxiosRequestConfig;
  }
) => {
  const { swr: swrOptions, axios: axiosOptions } = options ?? {};

  const isEnabled = swrOptions?.enabled !== false;
  const swrKey =
    swrOptions?.swrKey ?? (() => (isEnabled ? getAdminSettingControllerFindAllKey(params) : null));
  const swrFn = () => adminSettingControllerFindAll(params, axiosOptions);

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query
  };
};

export const adminSettingControllerUpdate = (
  updateSettingDto: UpdateSettingDto,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<void>> => {
  return axios.put('/admin/settings', updateSettingDto, options);
};

export const getAdminSettingControllerUpdateMutationFetcher = (options?: AxiosRequestConfig) => {
  return (_: string, { arg }: { arg: UpdateSettingDto }): Promise<AxiosResponse<void>> => {
    return adminSettingControllerUpdate(arg, options);
  };
};
export const getAdminSettingControllerUpdateMutationKey = () => '/admin/settings' as const;

export type AdminSettingControllerUpdateMutationResult = NonNullable<
  Awaited<ReturnType<typeof adminSettingControllerUpdate>>
>;
export type AdminSettingControllerUpdateMutationError = AxiosError<unknown>;

export const useAdminSettingControllerUpdate = <TError = AxiosError<unknown>>(options?: {
  swr?: SWRMutationConfiguration<
    Awaited<ReturnType<typeof adminSettingControllerUpdate>>,
    TError,
    string,
    UpdateSettingDto,
    Awaited<ReturnType<typeof adminSettingControllerUpdate>>
  > & { swrKey?: string };
  axios?: AxiosRequestConfig;
}) => {
  const { swr: swrOptions, axios: axiosOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getAdminSettingControllerUpdateMutationKey();
  const swrFn = getAdminSettingControllerUpdateMutationFetcher(axiosOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query
  };
};

export const adminSettingControllerBulkUpdate = (
  bulkUpdateSettingDto: BulkUpdateSettingDto,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<void>> => {
  return axios.put('/admin/settings/bulk', bulkUpdateSettingDto, options);
};

export const getAdminSettingControllerBulkUpdateMutationFetcher = (
  options?: AxiosRequestConfig
) => {
  return (_: string, { arg }: { arg: BulkUpdateSettingDto }): Promise<AxiosResponse<void>> => {
    return adminSettingControllerBulkUpdate(arg, options);
  };
};
export const getAdminSettingControllerBulkUpdateMutationKey = () => '/admin/settings/bulk' as const;

export type AdminSettingControllerBulkUpdateMutationResult = NonNullable<
  Awaited<ReturnType<typeof adminSettingControllerBulkUpdate>>
>;
export type AdminSettingControllerBulkUpdateMutationError = AxiosError<unknown>;

export const useAdminSettingControllerBulkUpdate = <TError = AxiosError<unknown>>(options?: {
  swr?: SWRMutationConfiguration<
    Awaited<ReturnType<typeof adminSettingControllerBulkUpdate>>,
    TError,
    string,
    BulkUpdateSettingDto,
    Awaited<ReturnType<typeof adminSettingControllerBulkUpdate>>
  > & { swrKey?: string };
  axios?: AxiosRequestConfig;
}) => {
  const { swr: swrOptions, axios: axiosOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getAdminSettingControllerBulkUpdateMutationKey();
  const swrFn = getAdminSettingControllerBulkUpdateMutationFetcher(axiosOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query
  };
};

export const healthControllerCheck = (
  options?: AxiosRequestConfig
): Promise<AxiosResponse<void>> => {
  return axios.get('/health', options);
};

export const getHealthControllerCheckKey = () => ['/health'] as const;

export type HealthControllerCheckQueryResult = NonNullable<
  Awaited<ReturnType<typeof healthControllerCheck>>
>;
export type HealthControllerCheckQueryError = AxiosError<unknown>;

export const useHealthControllerCheck = <TError = AxiosError<unknown>>(options?: {
  swr?: SWRConfiguration<Awaited<ReturnType<typeof healthControllerCheck>>, TError> & {
    swrKey?: Key;
    enabled?: boolean;
  };
  axios?: AxiosRequestConfig;
}) => {
  const { swr: swrOptions, axios: axiosOptions } = options ?? {};

  const isEnabled = swrOptions?.enabled !== false;
  const swrKey = swrOptions?.swrKey ?? (() => (isEnabled ? getHealthControllerCheckKey() : null));
  const swrFn = () => healthControllerCheck(axiosOptions);

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query
  };
};

export const systemLogControllerList = (
  options?: AxiosRequestConfig
): Promise<AxiosResponse<void>> => {
  return axios.get('/admin/system-logs', options);
};

export const getSystemLogControllerListKey = () => ['/admin/system-logs'] as const;

export type SystemLogControllerListQueryResult = NonNullable<
  Awaited<ReturnType<typeof systemLogControllerList>>
>;
export type SystemLogControllerListQueryError = AxiosError<unknown>;

export const useSystemLogControllerList = <TError = AxiosError<unknown>>(options?: {
  swr?: SWRConfiguration<Awaited<ReturnType<typeof systemLogControllerList>>, TError> & {
    swrKey?: Key;
    enabled?: boolean;
  };
  axios?: AxiosRequestConfig;
}) => {
  const { swr: swrOptions, axios: axiosOptions } = options ?? {};

  const isEnabled = swrOptions?.enabled !== false;
  const swrKey = swrOptions?.swrKey ?? (() => (isEnabled ? getSystemLogControllerListKey() : null));
  const swrFn = () => systemLogControllerList(axiosOptions);

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query
  };
};

export const systemLogControllerStats = (
  params: SystemLogControllerStatsParams,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<void>> => {
  return axios.get('/admin/system-logs/stats', {
    ...options,
    params: { ...params, ...options?.params }
  });
};

export const getSystemLogControllerStatsKey = (params: SystemLogControllerStatsParams) =>
  ['/admin/system-logs/stats', ...(params ? [params] : [])] as const;

export type SystemLogControllerStatsQueryResult = NonNullable<
  Awaited<ReturnType<typeof systemLogControllerStats>>
>;
export type SystemLogControllerStatsQueryError = AxiosError<unknown>;

export const useSystemLogControllerStats = <TError = AxiosError<unknown>>(
  params: SystemLogControllerStatsParams,
  options?: {
    swr?: SWRConfiguration<Awaited<ReturnType<typeof systemLogControllerStats>>, TError> & {
      swrKey?: Key;
      enabled?: boolean;
    };
    axios?: AxiosRequestConfig;
  }
) => {
  const { swr: swrOptions, axios: axiosOptions } = options ?? {};

  const isEnabled = swrOptions?.enabled !== false;
  const swrKey =
    swrOptions?.swrKey ?? (() => (isEnabled ? getSystemLogControllerStatsKey(params) : null));
  const swrFn = () => systemLogControllerStats(params, axiosOptions);

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query
  };
};

export const systemLogControllerFindOne = (
  id: string,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<void>> => {
  return axios.get(`/admin/system-logs/${id}`, options);
};

export const getSystemLogControllerFindOneKey = (id: string) =>
  [`/admin/system-logs/${id}`] as const;

export type SystemLogControllerFindOneQueryResult = NonNullable<
  Awaited<ReturnType<typeof systemLogControllerFindOne>>
>;
export type SystemLogControllerFindOneQueryError = AxiosError<unknown>;

export const useSystemLogControllerFindOne = <TError = AxiosError<unknown>>(
  id: string,
  options?: {
    swr?: SWRConfiguration<Awaited<ReturnType<typeof systemLogControllerFindOne>>, TError> & {
      swrKey?: Key;
      enabled?: boolean;
    };
    axios?: AxiosRequestConfig;
  }
) => {
  const { swr: swrOptions, axios: axiosOptions } = options ?? {};

  const isEnabled = swrOptions?.enabled !== false && !!id;
  const swrKey =
    swrOptions?.swrKey ?? (() => (isEnabled ? getSystemLogControllerFindOneKey(id) : null));
  const swrFn = () => systemLogControllerFindOne(id, axiosOptions);

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query
  };
};

export const systemLogControllerCleanup = (
  params: SystemLogControllerCleanupParams,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<void>> => {
  return axios.delete('/admin/system-logs/cleanup', {
    ...options,
    params: { ...params, ...options?.params }
  });
};

export const getSystemLogControllerCleanupMutationFetcher = (
  params: SystemLogControllerCleanupParams,
  options?: AxiosRequestConfig
) => {
  return (_: string, __: { arg: Arguments }): Promise<AxiosResponse<void>> => {
    return systemLogControllerCleanup(params, options);
  };
};
export const getSystemLogControllerCleanupMutationKey = () => '/admin/system-logs/cleanup' as const;

export type SystemLogControllerCleanupMutationResult = NonNullable<
  Awaited<ReturnType<typeof systemLogControllerCleanup>>
>;
export type SystemLogControllerCleanupMutationError = AxiosError<unknown>;

export const useSystemLogControllerCleanup = <TError = AxiosError<unknown>>(
  params: SystemLogControllerCleanupParams,
  options?: {
    swr?: SWRMutationConfiguration<
      Awaited<ReturnType<typeof systemLogControllerCleanup>>,
      TError,
      string,
      Arguments,
      Awaited<ReturnType<typeof systemLogControllerCleanup>>
    > & { swrKey?: string };
    axios?: AxiosRequestConfig;
  }
) => {
  const { swr: swrOptions, axios: axiosOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getSystemLogControllerCleanupMutationKey();
  const swrFn = getSystemLogControllerCleanupMutationFetcher(params, axiosOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query
  };
};

export const clientLogControllerReport = (
  clientErrorDto: ClientErrorDto,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<void>> => {
  return axios.post('/logs/client-error', clientErrorDto, options);
};

export const getClientLogControllerReportMutationFetcher = (options?: AxiosRequestConfig) => {
  return (_: string, { arg }: { arg: ClientErrorDto }): Promise<AxiosResponse<void>> => {
    return clientLogControllerReport(arg, options);
  };
};
export const getClientLogControllerReportMutationKey = () => '/logs/client-error' as const;

export type ClientLogControllerReportMutationResult = NonNullable<
  Awaited<ReturnType<typeof clientLogControllerReport>>
>;
export type ClientLogControllerReportMutationError = AxiosError<unknown>;

export const useClientLogControllerReport = <TError = AxiosError<unknown>>(options?: {
  swr?: SWRMutationConfiguration<
    Awaited<ReturnType<typeof clientLogControllerReport>>,
    TError,
    string,
    ClientErrorDto,
    Awaited<ReturnType<typeof clientLogControllerReport>>
  > & { swrKey?: string };
  axios?: AxiosRequestConfig;
}) => {
  const { swr: swrOptions, axios: axiosOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getClientLogControllerReportMutationKey();
  const swrFn = getClientLogControllerReportMutationFetcher(axiosOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query
  };
};

export const backupControllerDownload = (
  options?: AxiosRequestConfig
): Promise<AxiosResponse<void>> => {
  return axios.get('/admin/backup/download', options);
};

export const getBackupControllerDownloadKey = () => ['/admin/backup/download'] as const;

export type BackupControllerDownloadQueryResult = NonNullable<
  Awaited<ReturnType<typeof backupControllerDownload>>
>;
export type BackupControllerDownloadQueryError = AxiosError<unknown>;

export const useBackupControllerDownload = <TError = AxiosError<unknown>>(options?: {
  swr?: SWRConfiguration<Awaited<ReturnType<typeof backupControllerDownload>>, TError> & {
    swrKey?: Key;
    enabled?: boolean;
  };
  axios?: AxiosRequestConfig;
}) => {
  const { swr: swrOptions, axios: axiosOptions } = options ?? {};

  const isEnabled = swrOptions?.enabled !== false;
  const swrKey =
    swrOptions?.swrKey ?? (() => (isEnabled ? getBackupControllerDownloadKey() : null));
  const swrFn = () => backupControllerDownload(axiosOptions);

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query
  };
};

export const publicMaintenanceControllerGetStatus = (
  options?: AxiosRequestConfig
): Promise<AxiosResponse<void>> => {
  return axios.get('/settings/public/maintenance', options);
};

export const getPublicMaintenanceControllerGetStatusKey = () =>
  ['/settings/public/maintenance'] as const;

export type PublicMaintenanceControllerGetStatusQueryResult = NonNullable<
  Awaited<ReturnType<typeof publicMaintenanceControllerGetStatus>>
>;
export type PublicMaintenanceControllerGetStatusQueryError = AxiosError<unknown>;

export const usePublicMaintenanceControllerGetStatus = <TError = AxiosError<unknown>>(options?: {
  swr?: SWRConfiguration<
    Awaited<ReturnType<typeof publicMaintenanceControllerGetStatus>>,
    TError
  > & { swrKey?: Key; enabled?: boolean };
  axios?: AxiosRequestConfig;
}) => {
  const { swr: swrOptions, axios: axiosOptions } = options ?? {};

  const isEnabled = swrOptions?.enabled !== false;
  const swrKey =
    swrOptions?.swrKey ?? (() => (isEnabled ? getPublicMaintenanceControllerGetStatusKey() : null));
  const swrFn = () => publicMaintenanceControllerGetStatus(axiosOptions);

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query
  };
};

export const adminMaintenanceControllerGetSetting = (
  options?: AxiosRequestConfig
): Promise<AxiosResponse<void>> => {
  return axios.get('/admin/maintenance', options);
};

export const getAdminMaintenanceControllerGetSettingKey = () => ['/admin/maintenance'] as const;

export type AdminMaintenanceControllerGetSettingQueryResult = NonNullable<
  Awaited<ReturnType<typeof adminMaintenanceControllerGetSetting>>
>;
export type AdminMaintenanceControllerGetSettingQueryError = AxiosError<unknown>;

export const useAdminMaintenanceControllerGetSetting = <TError = AxiosError<unknown>>(options?: {
  swr?: SWRConfiguration<
    Awaited<ReturnType<typeof adminMaintenanceControllerGetSetting>>,
    TError
  > & { swrKey?: Key; enabled?: boolean };
  axios?: AxiosRequestConfig;
}) => {
  const { swr: swrOptions, axios: axiosOptions } = options ?? {};

  const isEnabled = swrOptions?.enabled !== false;
  const swrKey =
    swrOptions?.swrKey ?? (() => (isEnabled ? getAdminMaintenanceControllerGetSettingKey() : null));
  const swrFn = () => adminMaintenanceControllerGetSetting(axiosOptions);

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query
  };
};

export const adminMaintenanceControllerToggle = (
  options?: AxiosRequestConfig
): Promise<AxiosResponse<void>> => {
  return axios.put('/admin/maintenance/toggle', undefined, options);
};

export const getAdminMaintenanceControllerToggleMutationFetcher = (
  options?: AxiosRequestConfig
) => {
  return (_: string, __: { arg: Arguments }): Promise<AxiosResponse<void>> => {
    return adminMaintenanceControllerToggle(options);
  };
};
export const getAdminMaintenanceControllerToggleMutationKey = () =>
  '/admin/maintenance/toggle' as const;

export type AdminMaintenanceControllerToggleMutationResult = NonNullable<
  Awaited<ReturnType<typeof adminMaintenanceControllerToggle>>
>;
export type AdminMaintenanceControllerToggleMutationError = AxiosError<unknown>;

export const useAdminMaintenanceControllerToggle = <TError = AxiosError<unknown>>(options?: {
  swr?: SWRMutationConfiguration<
    Awaited<ReturnType<typeof adminMaintenanceControllerToggle>>,
    TError,
    string,
    Arguments,
    Awaited<ReturnType<typeof adminMaintenanceControllerToggle>>
  > & { swrKey?: string };
  axios?: AxiosRequestConfig;
}) => {
  const { swr: swrOptions, axios: axiosOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getAdminMaintenanceControllerToggleMutationKey();
  const swrFn = getAdminMaintenanceControllerToggleMutationFetcher(axiosOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query
  };
};

export const adminMaintenanceControllerUpdateMessage = (
  updateMaintenanceMessageDto: UpdateMaintenanceMessageDto,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<void>> => {
  return axios.put('/admin/maintenance/message', updateMaintenanceMessageDto, options);
};

export const getAdminMaintenanceControllerUpdateMessageMutationFetcher = (
  options?: AxiosRequestConfig
) => {
  return (
    _: string,
    { arg }: { arg: UpdateMaintenanceMessageDto }
  ): Promise<AxiosResponse<void>> => {
    return adminMaintenanceControllerUpdateMessage(arg, options);
  };
};
export const getAdminMaintenanceControllerUpdateMessageMutationKey = () =>
  '/admin/maintenance/message' as const;

export type AdminMaintenanceControllerUpdateMessageMutationResult = NonNullable<
  Awaited<ReturnType<typeof adminMaintenanceControllerUpdateMessage>>
>;
export type AdminMaintenanceControllerUpdateMessageMutationError = AxiosError<unknown>;

export const useAdminMaintenanceControllerUpdateMessage = <TError = AxiosError<unknown>>(options?: {
  swr?: SWRMutationConfiguration<
    Awaited<ReturnType<typeof adminMaintenanceControllerUpdateMessage>>,
    TError,
    string,
    UpdateMaintenanceMessageDto,
    Awaited<ReturnType<typeof adminMaintenanceControllerUpdateMessage>>
  > & { swrKey?: string };
  axios?: AxiosRequestConfig;
}) => {
  const { swr: swrOptions, axios: axiosOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getAdminMaintenanceControllerUpdateMessageMutationKey();
  const swrFn = getAdminMaintenanceControllerUpdateMessageMutationFetcher(axiosOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query
  };
};

export const adminMaintenanceControllerAddIp = (
  addAllowedIpDto: AddAllowedIpDto,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<void>> => {
  return axios.post('/admin/maintenance/allowed-ips', addAllowedIpDto, options);
};

export const getAdminMaintenanceControllerAddIpMutationFetcher = (options?: AxiosRequestConfig) => {
  return (_: string, { arg }: { arg: AddAllowedIpDto }): Promise<AxiosResponse<void>> => {
    return adminMaintenanceControllerAddIp(arg, options);
  };
};
export const getAdminMaintenanceControllerAddIpMutationKey = () =>
  '/admin/maintenance/allowed-ips' as const;

export type AdminMaintenanceControllerAddIpMutationResult = NonNullable<
  Awaited<ReturnType<typeof adminMaintenanceControllerAddIp>>
>;
export type AdminMaintenanceControllerAddIpMutationError = AxiosError<unknown>;

export const useAdminMaintenanceControllerAddIp = <TError = AxiosError<unknown>>(options?: {
  swr?: SWRMutationConfiguration<
    Awaited<ReturnType<typeof adminMaintenanceControllerAddIp>>,
    TError,
    string,
    AddAllowedIpDto,
    Awaited<ReturnType<typeof adminMaintenanceControllerAddIp>>
  > & { swrKey?: string };
  axios?: AxiosRequestConfig;
}) => {
  const { swr: swrOptions, axios: axiosOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getAdminMaintenanceControllerAddIpMutationKey();
  const swrFn = getAdminMaintenanceControllerAddIpMutationFetcher(axiosOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query
  };
};

export const adminMaintenanceControllerRemoveIp = (
  ip: string,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<void>> => {
  return axios.delete(`/admin/maintenance/allowed-ips/${ip}`, options);
};

export const getAdminMaintenanceControllerRemoveIpMutationFetcher = (
  ip: string,
  options?: AxiosRequestConfig
) => {
  return (_: string, __: { arg: Arguments }): Promise<AxiosResponse<void>> => {
    return adminMaintenanceControllerRemoveIp(ip, options);
  };
};
export const getAdminMaintenanceControllerRemoveIpMutationKey = (ip: string) =>
  `/admin/maintenance/allowed-ips/${ip}` as const;

export type AdminMaintenanceControllerRemoveIpMutationResult = NonNullable<
  Awaited<ReturnType<typeof adminMaintenanceControllerRemoveIp>>
>;
export type AdminMaintenanceControllerRemoveIpMutationError = AxiosError<unknown>;

export const useAdminMaintenanceControllerRemoveIp = <TError = AxiosError<unknown>>(
  ip: string,
  options?: {
    swr?: SWRMutationConfiguration<
      Awaited<ReturnType<typeof adminMaintenanceControllerRemoveIp>>,
      TError,
      string,
      Arguments,
      Awaited<ReturnType<typeof adminMaintenanceControllerRemoveIp>>
    > & { swrKey?: string };
    axios?: AxiosRequestConfig;
  }
) => {
  const { swr: swrOptions, axios: axiosOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getAdminMaintenanceControllerRemoveIpMutationKey(ip);
  const swrFn = getAdminMaintenanceControllerRemoveIpMutationFetcher(ip, axiosOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query
  };
};

export const adminMaintenanceControllerGetMyIp = (
  options?: AxiosRequestConfig
): Promise<AxiosResponse<void>> => {
  return axios.get('/admin/maintenance/my-ip', options);
};

export const getAdminMaintenanceControllerGetMyIpKey = () => ['/admin/maintenance/my-ip'] as const;

export type AdminMaintenanceControllerGetMyIpQueryResult = NonNullable<
  Awaited<ReturnType<typeof adminMaintenanceControllerGetMyIp>>
>;
export type AdminMaintenanceControllerGetMyIpQueryError = AxiosError<unknown>;

export const useAdminMaintenanceControllerGetMyIp = <TError = AxiosError<unknown>>(options?: {
  swr?: SWRConfiguration<Awaited<ReturnType<typeof adminMaintenanceControllerGetMyIp>>, TError> & {
    swrKey?: Key;
    enabled?: boolean;
  };
  axios?: AxiosRequestConfig;
}) => {
  const { swr: swrOptions, axios: axiosOptions } = options ?? {};

  const isEnabled = swrOptions?.enabled !== false;
  const swrKey =
    swrOptions?.swrKey ?? (() => (isEnabled ? getAdminMaintenanceControllerGetMyIpKey() : null));
  const swrFn = () => adminMaintenanceControllerGetMyIp(axiosOptions);

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query
  };
};
