/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Base Code API
 * The Base Code API description
 * OpenAPI spec version: 1.0
 */

export type AdminSettingControllerFindAllParams = {
  group: string;
};
